#%RAML 1.0
---
title: RAML API
mediaType: application/json

/api:
  /foo:
    get:
      description: Get a single record
      responses:
        200:
          body:
            example: |
              {
                "message": "hello world."
              }
